# Generated by Django 5.1.4 on 2026-04-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('focus_area', models.CharField(max_length=120)),
                ('breakfast', models.TextField()),
                ('mid_morning', models.TextField()),
                ('lunch', models.TextField()),
                ('evening_snack', models.TextField()),
                ('dinner', models.TextField()),
                ('hydration_tip', models.TextField()),
                ('lifestyle_tip', models.TextField()),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
