# Generated by Django 6.0.3 on 2026-05-07 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_labtest"),
    ]

    operations = [
        migrations.AddField(
            model_name="labtest",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="lab_tests/"),
        ),
        migrations.CreateModel(
            name="LabTestBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patient_name", models.CharField(max_length=255)),
                ("patient_email", models.EmailField(max_length=254)),
                ("patient_phone", models.CharField(max_length=20)),
                ("appointment_date", models.DateField()),
                ("appointment_time", models.TimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lab_test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.labtest"
                    ),
                ),
            ],
        ),
    ]
