# Generated by Django 6.0.3 on 2026-05-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_labtest_photo_labtestbooking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="labtest",
            name="photo",
            field=models.URLField(blank=True, null=True),
        ),
    ]
