# Generated by Django 6.0.3 on 2026-05-07 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_labtest_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hospital",
            name="photo",
            field=models.URLField(blank=True, null=True),
        ),
    ]
